name: Deploy to web1EC2

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          proxy_host: ${{ secrets.SSH_HOST}}
          proxy_username: ${{ secrets.SSH_USERNAME }}
          proxy_port: ${{ secrets.SSH_PORT }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_passphrase: ${{ secrets.SSH_PASS }}

          host: ${{ secrets.SSH_HOST_WEB }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
            cd deploytestrepo
            git pull origin main

name: Deploy to EC2

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
            cd deploytestrepo
            git pull origin main