name: Deploy to EC2

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 43.207.0.24 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa; ssh ec2-user@43.207.0.24 "git pull origin main"'