name: Deploy to EC2 another

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/dp_bastion
          echo ${{ vars.SSH_PRIVATE_KEY }} > ~/.ssh/dp_bastion
          cat ~/.ssh/dp_bastion