name: deploytest workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          whoami
          echo "----"
          pwd
          echo "----"
          ls
          echo "----"
          echo $HOME
          echo "----"
          echo ~
          echo "----"
          # ssh-keyscan -H 43.207.0.24 >> $HOME/.ssh/known_hosts
          ssh -i ~/.ssh/dp_bastion -T ec2-user@43.207.0.24 "whoami && pwd && ls && cd deploytestrepo && git pull origin main"