name: Deploy to EC2

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/dp_bastion
          chmod 600 ~/.ssh/dp_bastion
          ssh-keyscan -H 43.207.0.24 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/dp_bastion ec2-user@43.207.0.24 'git pull origin main'
