name: Deploy to EC2 another

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/dp_bastion
          ls ~/.ssh
          echo ${{ vars.SSH_PRIVATE_KEY }} > ~/.ssh/dp_bastion
          chmod 600 ~/.ssh/dp_bastion
          sshpass -p "${{ vars.SSH_PASS }}" ssh -i ~/.ssh/dp_bastion ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} "pwd && ls"